### ISSUE TITLE
Systemd support

### ISSUE THREAD

**Issue by jakobjakobson13** [fedelibre/org.frescobaldi.Frescobaldi#1]
Hi Federico,

apparently `systemd` support can't be done within the flatpak package. [Mprime](https://github.com/flathub/org.mersenne.mprime/tree/master) that you have to enable systemd support system-wide parallel to the flatpak package installation.

But I guess you have to check that with someone that has a more profound knowledge of the flatpak system.

**Comment by fedelibre** [comment]
Hey Jakob, today I realized that granting access to all devices allows to see and access the MIDI synth running in the host (see the commit I've just pushed). IMO this is the best solution. I don't want to clutter Frescobaldi with optional bundles and I prefer leaving the choice of the MIDI synth to the user.
